### ISSUE TITLE
extension module SuffixTreec not available

### ISSUE THREAD

**Issue by fluffybeing** [JDonner/SuffixTree#2]
import SuffixTree
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "SuffixTree/**init**.py", line 1, in <module>
    from SubstringDict import SubstringDict
  File "SuffixTree/SubstringDict.py", line 1, in <module>
    from SuffixTree import SuffixTree
  File "SuffixTree/SuffixTree.py", line 2, in <module>
    import SuffixTreec
ImportError: No module named SuffixTreec

**Comment by michaelmior** [comment]
Did you compile the module?

`python setup.py build`
